- name: Bragi
  instr: f5560A
  mode: LAN
  address: 129.196.138.113
  port: '3490'
  gpib: '6'
- name: "V\xED\xF0arr"
  instr: f5730A
  mode: LAN
  address: 20.000.00.000
  port: '3490'
  gpib: '7'
- name: Sigurd
  instr: f8588A
  mode: LAN
  address: 10.205.92.63
  port: '3490'
  gpib: '8'
- name: Vidar
  instr: f884xA
  mode: GPIB
  address: 10.205.92.183
  port: '3490'
  gpib: '9'
- name: "Gr\xEDmhildr"
  instr: f884xA
  mode: GPIB
  address: 10.205.92.184
  port: '3490'
  gpib: '4'
